"use client";
import { FormEvent, useEffect, useState } from "react";
import { motion, useScroll, useSpring } from "framer-motion";
import { ArrowUpRight, BriefcaseBusiness, Check, ChevronDown, CircleUserRound, FileCheck2, Globe2, Mail, MapPin, Menu, Phone, Plane, Send, ShieldCheck, Star, UsersRound, X } from "lucide-react";

const countries = [["🇸🇬","Singapore"],["🇰🇷","South Korea"],["🇩🇪","Germany"],["🇵🇱","Poland"],["🇷🇴","Romania"],["🇱🇹","Lithuania"],["🇮🇹","Italy"],["🇲🇾","Malaysia"],["🇦🇪","Dubai"],["🇭🇺","Hungary"],["🇭🇷","Croatia"],["🇪🇺","Europe"]];
const jobs = ["Warehouse","Construction","Hotel","Restaurant","Factory","Delivery Driver","Cook","Cleaner","Technician","Healthcare","Hospitality","Agriculture","Logistics","Engineering"];
const testimonials = [
  ["Arun K.","Singapore","I received clear guidance at every step. I’m now working in Singapore with confidence."],["Priya S.","Germany","Truly professional documentation support and a transparent process."],["Mohamed R.","Dubai","My visa was approved smoothly. The team kept me informed throughout."],["Vijay P.","Poland","They helped turn a difficult career move into a wonderful opportunity."],["Sanjay M.","Romania","Honest advice, genuine job order, and amazing support before departure."],["Meena R.","Malaysia","The interview preparation was exactly what I needed."],["Karthik S.","Italy","From application to airport support, SHA & SHA were exceptional."],["Asha D.","South Korea","Their commitment to candidates is visible in every detail."],["Rajesh V.","Lithuania","Fast documentation and a very helpful team."],["Divya N.","Hungary","A trusted consultancy that truly cares about your future."],["Imran A.","Croatia","Professional, transparent and always available to answer questions."],["Lakshmi P.","Europe","They made my international career dream feel possible."]
];
const faqs = [["How long is visa processing?","Processing times differ by country and employer, but our team provides clear timelines and updates throughout."],["How much experience is required?","Requirements depend on the role. We work with both experienced professionals and qualified entry-level candidates."],["Do you provide accommodation?","Many employer offers include or help arrange accommodation. Your job offer will clearly state the available benefits."],["How can I apply?","Choose Apply Now, share your profile, and our recruitment team will contact you with suitable opportunities."]];
const reveal = { hidden:{opacity:0,y:28}, show:{opacity:1,y:0,transition:{duration:.65}} };
function SectionTitle({eyebrow,title,copy}:{eyebrow:string,title:string,copy?:string}){return <motion.div variants={reveal} initial="hidden" whileInView="show" viewport={{once:true,amount:.25}} className="section-title"><span>{eyebrow}</span><h2>{title}</h2>{copy&&<p>{copy}</p>}</motion.div>}
export default function Home(){
 const [menu,setMenu]=useState(false),[open,setOpen]=useState<number|null>(null),[submitted,setSubmitted]=useState(false); const {scrollYProgress}=useScroll(); const scaleX=useSpring(scrollYProgress,{stiffness:110,damping:30});
 useEffect(()=>{document.documentElement.style.scrollBehavior="smooth"},[]);
 const submit=(e:FormEvent)=>{e.preventDefault();setSubmitted(true)};
 return <main>
 <motion.div className="progress" style={{scaleX}} />
 <header><a href="#home" className="logo"><i>SHA</i><span>& SHA<br/><small>CONSULTANCY</small></span></a><nav className={menu?"open":""}>{["Home","About","Services","Countries","Jobs","Stories","Careers","Contact"].map(x=><a onClick={()=>setMenu(false)} key={x} href={`#${x.toLowerCase()}`}>{x}</a>)}<a className="nav-apply" href="#contact">Apply Now</a></nav><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Toggle menu">{menu?<X/>:<Menu/>}</button></header>
 <section id="home" className="hero"><div className="map-grid"/><div className="orb o1"/><div className="orb o2"/><div className="route r1"/><div className="route r2"/><div className="passport p1">VISA<br/><b>APPROVED</b></div><div className="passport p2">GLOBAL<br/><b>CAREERS</b></div><motion.div initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{duration:.8}} className="hero-copy"><p className="kicker"><span/> INTERNATIONAL RECRUITMENT CONSULTANCY</p><h1>Your gateway<br/>to <em>global</em> careers.</h1><p className="lede">Connecting skilled professionals with remarkable international opportunities.</p><div className="actions"><a className="button gold" href="#contact">Apply now <ArrowUpRight/></a><a className="button ghost" href="#jobs">View jobs</a></div></motion.div><div className="hero-meta"><span><b>10+</b> years of trust</span><span><b>20+</b> countries</span><span><b>98%</b> visa success</span></div><div className="flight"><Plane/> <span>CHENNAI</span><i/> <span>THE WORLD</span></div></section>
 <section id="about" className="about section"><div className="art-frame"><div className="art-photo"/><div className="stamp">SINCE<br/><b>2015</b></div><div className="art-card"><Globe2/><span>Opportunities<br/>without borders.</span></div></div><div><SectionTitle eyebrow="ABOUT SHA & SHA" title="A considered path to your next chapter." copy="We pair personal guidance with global reach — helping skilled professionals move forward with confidence, clarity and integrity."/><div className="about-points"><div><Check/> Ethical & transparent</div><div><Check/> Personal guidance</div><div><Check/> Global opportunities</div></div><a className="text-link" href="#contact">Discover our approach <ArrowUpRight/></a></div></section>
 <section className="philosophy"><div><span>OUR VISION</span><p>“To become one of the most trusted international recruitment consultancies by connecting talented professionals with global career opportunities.”</p></div><div><span>OUR MISSION</span><p>“To provide ethical, reliable and efficient overseas recruitment solutions that help individuals achieve successful international careers.”</p></div></section>
 <section id="countries" className="section"><SectionTitle eyebrow="GLOBAL DESTINATIONS" title="Where ambition takes you." copy="Explore compelling opportunities across established international markets."/><div className="country-grid">{countries.map(([flag,name],i)=><motion.article whileHover={{y:-8}} key={name} className="country"><span>{flag}</span><b>{name}</b><ArrowUpRight/></motion.article>)}</div></section>
 <section id="jobs" className="jobs section"><SectionTitle eyebrow="OPPORTUNITIES" title="Work that moves you forward."/><div className="job-grid">{jobs.map((job,i)=><motion.a whileHover={{scale:1.025}} href="#contact" key={job}><BriefcaseBusiness/><span>0{i+3}</span><b>{job}</b><ArrowUpRight/></motion.a>)}</div></section>
 <section id="services" className="services section"><SectionTitle eyebrow="OUR SERVICES" title="Every detail, expertly handled."/><div className="service-grid">{[[ShieldCheck,"Visa Assistance"],[FileCheck2,"Documentation"],[UsersRound,"Interview Preparation"],[CircleUserRound,"Resume Guidance"],[Globe2,"Work Permit Processing"],[Plane,"Airport Assistance"],[Phone,"Candidate Support"],[BriefcaseBusiness,"Employer Coordination"]].map(([Icon,name]:any)=><motion.div whileHover={{y:-7}} key={name}><Icon/><h3>{name}</h3><p>Dedicated support delivered with precision, care and complete transparency.</p><ArrowUpRight/></motion.div>)}</div></section>
 <section className="process"><SectionTitle eyebrow="THE JOURNEY" title="A clear route, from here to there."/><div className="timeline">{["Apply","Document Verification","Interview","Employer Selection","Visa Processing","Ticket Booking","Fly Abroad"].map((x,i)=><motion.div initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.08}} key={x}><b>0{i+1}</b><i/ ><span>{x}</span></motion.div>)}</div></section>
 <section id="stories" className="stories section"><SectionTitle eyebrow="SUCCESS STORIES" title="Real journeys. Real momentum."/><div className="story-grid"><article className="story main-story"><div className="story-image one"/><div><small>GERMANY · WAREHOUSE ASSOCIATE</small><h3>From ambition to arrival.</h3><p>Visa Approved · €1,900 / month</p></div></article><article className="story"><div className="story-image two"/><div><small>SINGAPORE · HOSPITALITY</small><h3>A career beyond borders.</h3><p>Visa Approved · S$2,400 / month</p></div></article><article className="story"><div className="story-image three"/><div><small>POLAND · TECHNICIAN</small><h3>Building a global future.</h3><p>Visa Approved · €1,700 / month</p></div></article></div></section>
 <section className="stats"><div><b>5000<span>+</span></b><p>Candidates Placed</p></div><div><b>100<span>+</span></b><p>Partner Companies</p></div><div><b>20<span>+</span></b><p>Countries</p></div><div><b>98<span>%</span></b><p>Client Satisfaction</p></div></section>
 <section className="testimonials section"><SectionTitle eyebrow="CANDIDATE VOICES" title="Trusted by people going places."/><div className="testimonial-track">{[...testimonials,...testimonials].map(([name,country,review],i)=><article key={i}><div><span className="avatar">{name[0]}</span><span><b>{name}</b><small>{country}</small></span><div className="stars">★★★★★</div></div><p>“{review}”</p></article>)}</div></section>
 <section id="careers" className="careers"><div><p className="kicker"><span/> JOIN OUR TEAM</p><h2>Build futures.<br/><em>Including yours.</em></h2><p>We are looking for people who lead with empathy and have a true appetite for excellence.</p><a href="#contact" className="button gold">See openings <ArrowUpRight/></a></div><div className="roles">{["HR Executive","Marketing","Documentation Executive","Business Development","Digital Marketing","Graphic Designer"].map((x,i)=><a href="#contact" key={x}><span>0{i+1}</span><b>{x}</b><ArrowUpRight/></a>)}</div></section>
 <section className="faq section"><SectionTitle eyebrow="FAQ" title="Questions, answered."/>{faqs.map(([q,a],i)=><div className="faq-item" key={q}><button onClick={()=>setOpen(open===i?null:i)}><b>{q}</b><ChevronDown className={open===i?"flip":""}/></button>{open===i&&<motion.p initial={{opacity:0,height:0}} animate={{opacity:1,height:"auto"}}>{a}</motion.p>}</div>)}</section>
 <section id="contact" className="contact"><div className="contact-info"><p className="kicker"><span/> START YOUR JOURNEY</p><h2>The world is<br/><em>waiting.</em></h2><p>Tell us a little about your career ambitions. Our team will guide your next move.</p><div className="details"><a href="tel:+919944409826"><Phone/> +91 9944409826</a><a href="mailto:hr.shaconsultancy@gmail.com"><Mail/> hr.shaconsultancy@gmail.com</a><span><MapPin/> Nagapattinam, Tamil Nadu, India</span></div></div><form onSubmit={submit}>{submitted?<div className="form-success"><Check/><h3>Thank you.</h3><p>Your application has been received. We’ll be in touch shortly.</p></div>:<><label>Full name<input required placeholder="Your name"/></label><label>Email address<input required type="email" placeholder="you@email.com"/></label><label>Interested role<select defaultValue=""><option value="" disabled>Select a role</option>{jobs.map(x=><option key={x}>{x}</option>)}</select></label><label>Message<textarea placeholder="Tell us about your experience"/></label><button className="button gold" type="submit">Send application <Send/></button></>}</form></section>
 <footer><a className="logo"><i>SHA</i><span>& SHA<br/><small>CONSULTANCY</small></span></a><p>Your Career Partner</p><div>{["Instagram","Facebook","LinkedIn","WhatsApp"].map(x=><a key={x} href="#">{x}</a>)}</div><small>© {new Date().getFullYear()} SHA & SHA CONSULTANCY. All rights reserved.</small></footer><a href="#home" className="to-top" aria-label="Back to top">↑</a>
 </main>
}
